### ISSUE TITLE
Is it works with Emotiv Insight?

### ISSUE THREAD

**Issue by indiejoseph** [charliegerard/Epoc.js#1]

**Comment by charliegerard** [comment]
I did write a version for the Insight but I didn't get time to include the code in the module yet.

**Comment by charliegerard** [comment]
@indiejoseph I've updated to use the latest SDK so it should now be working with the Insight & EPOC. If you get a chance to try it, please let me know if it's working fine :)

**Comment by piotrekkmt** [comment]
Hey Charlie, tested it on node v6.11.5 and the sample script is giving out that there's some missing files. (sorry it took that long btw)

```
~/Git/devfest17hackathon ⑂master*  node emotiv.js 
/Users/peterpoliwoda/Git/devfest17hackathon/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: dlopen(/Users/peterpoliwoda/Git/devfest17hackathon/node_modules/epocjs/build/Release/index.node, 1): Library not loaded: libedk.1.dylib
  Referenced from: /Users/peterpoliwoda/Git/devfest17hackathon/node_modules/epocjs/build/Release/index.node
  Reason: image not found
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/peterpoliwoda/Git/devfest17hackathon/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/peterpoliwoda/Git/devfest17hackathon/node_modules/epocjs/index.js:3:31)
    at Module._compile (module.js:570:32)
```

**Comment by mustafayildirim** [comment]
I have an Insight, I'll try.

**Comment by markusvankempen** [comment]
I just got the emotiv insight and trying this ... 
quick q: what is the .emu file and how does one create one ?

**Comment by manifestinteractive** [comment]
@markusvankempen if you figure out how to make the .emu file, let me know.  Just posted issue #7 for this if you are still looking for an answer too.
